### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by buttim** [erincandescent/nuvoprog#4]
I get the following errors (Win10, Go 1.15.3):

`# github.com/karalabe/hid
In file included from go\src\github.com\karalabe\hid\hid_enabled.go:40:
go\src\github.com\karalabe\hid/hidapi/windows/hid.c: In function 'hid_enumerate':
go\src\github.com\karalabe\hid/hidapi/windows/hid.c:431:5: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
  431 |     strncpy(cur_dev->path, str, len+1);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
go\src\github.com\karalabe\hid/hidapi/windows/hid.c:429:11: note: length computed here
  429 |     len = strlen(str);
      |           ^~~~~~~~~~~
# github.com/erincandescent/nuvoprog
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-cygwin/9.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/9.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status`

**Comment by erincandescent** [comment]
It looks like your setup is somehow attempting to link code compiled for MinGW using the Cygwin linker

**Comment by buttim** [comment]
I think you are right; I fiddled with my PATH environment variable and the error disappeared. Still not installing with a "unrecognized option '--high-entropy-va'" error message though, but I think this issue can be safely closed. Thanks for your help

**Comment by buttim** [comment]
BTW this is not a nuvoprog problem but a go language limitation under Windows. I solved  it using TDM-GCC which supports a more recent version of ld supporting the unrecognized option. Thanks for your help and keep on the good work!
