### ISSUE TITLE
Unsupported device. But not for real

### ISSUE THREAD

**Issue by shining-fnml** [erincandescent/nuvoprog#5]
Hi, and thank you for your wonderful code.
I've bought a Nu-link clone from [Amazon](https://www.amazon.it/gp/product/B07KSFRPX6/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1) that is detected as follows by lsusb:
_Bus 002 Device 066: ID 0416:511c Winbond Electronics Corp._
nuvoprog detects is as well:
_[0002:0041:00]       0x00012009 - Firmware Version 6875_
But when I
`run nuvoprog read -t n76e003 dev.ihx`
I get an "Unsupported device" message.
It comes from **cmd/connection.go** at line 97. So I printed the mismatching values in the above condition and these are the results:
devID: 0x00ff3650, targetDev.DeviceID: N76E003
The actual mcu is a N76E003At20.
Maybe this short trunk from the verbose output can help in identifying the problem:
_2020/11/20 02:45:19 Checking device ID
2020/11/20 02:45:19 >  0508a300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
2020/11/20 02:45:19 <  0508a30000005036ff001894f784370106010000200000001f45316dd43d4dd0540f330eb703cd5cdc841b249d39763e8fbd226e31a9aab37ededb60ff3230b7
2020/11/20 02:45:19 OK, Device ID  0x00ff3650_
Then I tried to bypass the check at line 96 and everything went fine. I flashed a simple program and it runs smoothly on my board.
I hope you can easily fix it or give me instructions about what to check next.

Regards

**Comment by erincandescent** [comment]
This looks related to #3 - I never added support for locked devices. It looks reasonably straightforward though

(Closing this in favor of that issue)
